import Head from "next/head";
import CardList from "@/components/cardList";
import styles from "@/styles/Home.module.scss";

// Client Side
export default function Home() {
  return (
    <>
      <Head>
        <title>8 Settembre 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CardList title="Divina Commedia" />
      </main>
    </>
  );
}

// Server Side
// export function getServerSideProps(ctx) {
//   console.log(ctx);

//   return {
//     props: {
//       status: "ok",
//     },
//   };
// }
