import Head from "next/head";
import styles from "@/styles/Home.module.css";

interface User {
  id: number;
  name: string;
  surname: string;
  age: number;
}

interface Data {
  data: User[];
  offset: number;
}

export default function Home({ data }: Data) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {data?.data.map((user: User) => (
          <div>
            <h3>{user.name}</h3>
            <h4>{user.surname}</h4>
            <p>{user.age}</p>
          </div>
        ))}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3001/api/users");
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
