import { useState, useEffect } from "react";
import Head from "next/head";
import { ItemData } from "@/types/general";
import ListItem from "@/components/listItem";
import AddItem from "@/components/addItem";

import { HTTP_GET } from "./utils/fn";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const [listItemData, setListItemData] = useState<ItemData[]>([]);
  const [listItemDataLoading, setListItemDataLoading] =
    useState<boolean>(false);

  useEffect(() => {
    HTTP_GET("/api/getList").then(({ list }) => {
      setListItemDataLoading(true);
      setListItemData(list.data);
    });
  }, [listItemDataLoading]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Typescript Todo List</h1>
        <AddItem setListItemDataLoading={setListItemDataLoading} />
        {listItemDataLoading ? (
          <ListItem
            data={listItemData}
            setListItemDataLoading={setListItemDataLoading}
          />
        ) : (
          <p>Loading...</p>
        )}
      </main>
    </>
  );
}
